image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-f PipeItUp/pom.xml --batch-mode  --errors --fail-at-end --show-version"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
