package ch.fhnw.ip12.pipeitup.ui.views.touch;

import ch.fhnw.ip12.pipeitup.app.ExcludeTypeFromJacocoGeneratedReport;

@ExcludeTypeFromJacocoGeneratedReport
public enum TouchScene {
	START_SCREEN, MAIN_MENU, GAMEMODE_MENU, EXPLAINMODE, GAMEMODE, EXPLAINMODE_PRIM, EXPLAINMODE_KRUSKAL, HIGHSCORE_PRIM, HIGHSCRORE_KRUSKAL, GAMEMODE_PRIM, GAMEMODE_KRUSKAL, KRUSKAL_SPIEL_STEP_2,
	PRIM_SPIEL_STEP_2, PRIM_NAMEN_EINGEBEN, PLAYER, PREGAMESCREEN, RUN, END, PAULINE1, PAULINE2, PAULINE3, PAULINE4, PAULINE5, SETTINGS,TURNOFF, DELETE_HIGHSCORE,
	SPIELMECHANIK_P1, SPIELMECHANIK_P2, SPIELMECHANIK_P3, SPIELMECHANIK_P4, SPIELMECHANIK_P5, SPIELMECHANIK_P6, SPIELMECHANIK_P7, EM_PRIM1, EM_PRIM2, EM_PRIM3, EM_PRIM4, EM_PRIM5, EM_PRIM6, SPIELMECHANIK_K1, SPIELMECHANIK_K2, SPIELMECHANIK_K3, SPIELMECHANIK_K4,SPIELMECHANIK_K5, SPIELMECHANIK_K6, SPIELMECHANIK_K7, EM_KRUSKAL1, EM_KRUSKAL2, EM_KRUSKAL3, EM_KRUSKAL4, EM_KRUSKAL5;
}

