package ch.fhnw.ip12.pipeitup.ui.views.touch;

public enum TouchScene {
	START_SCREEN, MAIN_MENU, GAMEMODE_MENU, EXPLAINMODE, GAMEMODE, EXPLAINMODE_PRIM, EXPLAINMODE_KRUSKAL, HIGHSCORE_PRIM, HIGHSCRORE_KRUSKAL
}

